import PolicyPage from '../components/PolicyPage'
export default function EditorialPolicy(){return <PolicyPage eyebrow="EDITORIAL POLICY" title="Independent review with visible accountability." intro="AGP’s editorial process is designed to improve research quality without compromising author ownership or manuscript confidentiality." updated="5 October 2026" sections={[
{title:'Editorial stages',paragraphs:['Submissions may move through desk review, editorial review, source checking, revision, approval, scheduling and publication. Not every submission will pass every stage, and AGP may request additional evidence or clarification where necessary.']},
{title:'Assignment and confidentiality',paragraphs:['Unpublished manuscripts are only available to authorised personnel assigned to the submission. Assigned reviewers must accept the confidentiality and non-use statement and declare conflicts before accessing manuscript content.']},
{title:'Conflicts of interest',paragraphs:['Editors and reviewers must recuse themselves where a personal, professional, financial or other relationship could reasonably call impartiality into question.']},
{title:'Source integrity',paragraphs:['Editors may check citations, links, datasets, quotations, claims and methodology. Authors are responsible for providing sufficient information to enable reasonable verification.']},
{title:'AI-assisted work',paragraphs:['Use of AI tools does not remove author responsibility. Material AI assistance that affects analysis, writing, code, data processing or evidence should be disclosed where relevant. Editors must not upload confidential manuscripts to third-party generative AI services without author permission.']},
{title:'Corrections and retractions',paragraphs:['AGP may correct metadata or content, append editorial notices, withdraw material or retract a publication where serious errors, integrity concerns, legal issues or undisclosed conflicts materially affect the work.']}
]}/>} 
