import { ArrowRight, BarChart3, BookOpen, Eye, FileText, Globe2, Goal, Lock, Network, Scale, ShieldCheck, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import type { Publication } from '../types'

const pillars=[
  {icon:Globe2,title:'Geopolitics',text:'Power, diplomacy, security and Africa’s changing external relationships.'},
  {icon:BarChart3,title:'Political Economy',text:'Trade, investment, institutions, development and economic transformation.'},
  {icon:Network,title:'AI & Technology',text:'Digital policy, AI governance, infrastructure and technological sovereignty.'},
  {icon:ShieldCheck,title:'Governance',text:'Institutions, regulation, public policy and evidence-informed decision-making.'},
]

export default function Home(){
 const [pubs,setPubs]=useState<Publication[]>([])
 useEffect(()=>{api<Publication[]>('/publications').then(setPubs).catch(()=>{})},[])
 return <>
   <section className="hero"><div className="hero-grid"><div><div className="eyebrow">AFRICAN RESEARCH • POLICY INTELLIGENCE • GLOBAL POWER</div><h1>Africa needs more than commentary. It needs <em>connected evidence.</em></h1><p>AGP brings research, researchers, policy intelligence, data and public understanding into one professional African knowledge platform.</p><div className="hero-actions"><Link className="button lime large" to="/research">Explore research <ArrowRight size={18}/></Link><Link className="button outline-light large" to="/register">Join as a researcher</Link></div></div><div className="hero-panel"><div className="live-label">AGP KNOWLEDGE NETWORK</div><div className="network-visual"><span>Africa</span><i/><b>Research</b><b>Policy</b><b>Data</b><b>People</b></div><div className="hero-stats"><div><strong>54</strong><span>African countries</span></div><div><strong>1</strong><span>connected research layer</span></div></div></div></div></section>
   <section className="ticker"><span>TRACKING</span><strong>AI governance</strong><strong>AfCFTA</strong><strong>Critical minerals</strong><strong>Digital sovereignty</strong><strong>African agency</strong><strong>Political economy</strong></section>
   <section className="page section"><div className="section-head"><div><div className="eyebrow dark">LATEST INTELLIGENCE</div><h2>Research worth acting on.</h2></div><Link to="/research" className="text-link">View all research <ArrowRight size={16}/></Link></div><div className="publication-grid">{pubs.length?pubs.slice(0,3).map((p,i)=><Link to={`/research/${p.slug}`} className={`publication-card ${i===0?'featured':''}`} key={p.id}><div className="publication-meta"><span>{p.topic}</span><span>{p.region||p.country||'Africa'}</span></div><h3>{p.title}</h3><p>{p.abstract}</p><div className="author-line">{p.author?`${p.author.first_name} ${p.author.last_name}`:'AGP Research'} <span>•</span> {p.published_at?new Date(p.published_at).toLocaleDateString():''}</div></Link>):<div className="empty-card">Published AGP research will appear here.</div>}</div></section>
   <section className="dark-section"><div className="page section"><div className="eyebrow">WHY AGP</div><h2>From publication to policy relevance.</h2><div className="feature-grid">{pillars.map(({icon:Icon,title,text})=><div className="feature" key={title}><Icon/><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
   <section className="page section about-home"><div className="section-head"><div><div className="eyebrow dark">ABOUT US</div><h2>Built to strengthen African knowledge systems.</h2></div><Link className="text-link" to="/about">Read our full story <ArrowRight size={16}/></Link></div><p className="lead">Africa & Global Power is an independent research and knowledge platform created to make credible African research easier to produce, protect, discover, collaborate around and translate into public and policy relevance.</p><div className="mission-grid"><div className="card mission-card"><Goal/><h3>Goal</h3><p>Connect rigorous research, researchers, data and policy intelligence in one trusted platform.</p></div><div className="card mission-card"><Eye/><h3>Vision</h3><p>An Africa with stronger knowledge systems and greater agency in the debates shaping its future.</p></div><div className="card mission-card"><ShieldCheck/><h3>Mission</h3><p>Provide trustworthy publishing, research protection, collaboration and evidence tools built around African priorities.</p></div></div></section>
   <section className="page section legal-home"><div className="section-head"><div><div className="eyebrow dark">TRUST, PRIVACY & LEGAL</div><h2>Know the rules before you participate.</h2></div></div><p className="lead">AGP makes its responsibilities to researchers, readers and contributors visible. Review how we handle personal information, the terms governing use of the platform, and the safeguards surrounding research submissions.</p><div className="legal-home-grid"><Link className="card legal-home-card" to="/privacy"><Lock/><div><h3>Privacy Policy</h3><p>How AGP collects, uses, protects and manages account, manuscript and platform data.</p><span>Read Privacy Policy <ArrowRight size={15}/></span></div></Link><Link className="card legal-home-card" to="/terms"><Scale/><div><h3>Terms & Conditions</h3><p>Your responsibilities, author rights, AGP publishing permissions and platform rules.</p><span>Read Terms & Conditions <ArrowRight size={15}/></span></div></Link><Link className="card legal-home-card" to="/trust"><FileText/><div><h3>Trust Centre</h3><p>How Trust Vault, editorial controls, authentication and research-integrity safeguards work.</p><span>Open Trust Centre <ArrowRight size={15}/></span></div></Link></div></section>
   <section className="page section split"><div><div className="eyebrow dark">FOR RESEARCHERS</div><h2>Your work should travel further than a PDF.</h2><p className="lead">Build a professional profile, submit research through a transparent editorial workflow, protect original submissions, understand readership, amplify published work and collaborate with peers.</p><Link className="button dark large" to="/register">Create researcher profile <ArrowRight size={18}/></Link></div><div className="researcher-preview card"><div className="avatar">AGP</div><h3>Researcher workspace</h3><div className="preview-row"><BookOpen size={18}/> Publication analytics</div><div className="preview-row"><Users size={18}/> Research Rooms & messaging</div><div className="preview-row"><ShieldCheck size={18}/> Trust Vault & editorial history</div></div></section>
 </>
}
