import { MailPlus } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../lib/api'
import type { Message, User } from '../types'
export default function Messages(){const [params]=useSearchParams();const [box,setBox]=useState<'inbox'|'sent'>('inbox'),[items,setItems]=useState<Message[]>([]),[people,setPeople]=useState<User[]>([]),[compose,setCompose]=useState(!!params.get('to'));const [form,setForm]=useState({recipient_id:params.get('to')||'',subject:'',body:''})
 async function load(){setItems(await api<Message[]>(`/messages?box=${box}`))}useEffect(()=>{load()},[box]);useEffect(()=>{api<User[]>('/researchers').then(setPeople)},[])
 async function send(e:React.FormEvent){e.preventDefault();await api('/messages',{method:'POST',body:JSON.stringify(form)});setCompose(false);setForm({recipient_id:'',subject:'',body:''});setBox('sent');await load()}
 return <div className="page section"><div className="dashboard-head"><div><div className="eyebrow dark">AGP MESSAGES</div><h1>Research conversations.</h1><p>Communicate without publishing personal email addresses.</p></div><button className="button dark" onClick={()=>setCompose(true)}><MailPlus size={18}/> New message</button></div><div className="message-layout"><aside className="message-nav"><button className={box==='inbox'?'active':''} onClick={()=>setBox('inbox')}>Inbox</button><button className={box==='sent'?'active':''} onClick={()=>setBox('sent')}>Sent</button></aside><section className="card message-list">{compose&&<form className="compose" onSubmit={send}><h2>New message</h2><label>Researcher<select required value={form.recipient_id} onChange={e=>setForm({...form,recipient_id:e.target.value})}><option value="">Select researcher</option>{people.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><label>Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Message<textarea rows={7} required value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><div className="form-actions"><button className="button dark">Send</button><button type="button" className="button ghost" onClick={()=>setCompose(false)}>Cancel</button></div></form>}{!compose&&items.map(m=><div className={`message-row ${!m.is_read&&box==='inbox'?'unread':''}`} key={m.id}><div className="message-avatar">{(box==='inbox'?m.sender?.first_name:m.recipient?.first_name)?.[0]||'A'}</div><div><strong>{m.subject}</strong><span>{box==='inbox'?`${m.sender?.first_name} ${m.sender?.last_name}`:`To: ${m.recipient?.first_name} ${m.recipient?.last_name}`}</span><p>{m.body}</p></div><time>{new Date(m.created_at).toLocaleDateString()}</time></div>)}{!compose&&!items.length&&<div className="empty-inline">No messages in this folder.</div>}</section></div></div>}
