import PolicyPage from '../components/PolicyPage'
export default function Privacy(){return <PolicyPage eyebrow="PRIVACY POLICY" title="Your data should be handled with purpose and restraint." intro="This Privacy Policy explains what Africa & Global Power collects, why we use it, how we protect it and the choices available to users." updated="5 October 2026" sections={[
{title:'1. Scope',paragraphs:['This policy applies to AGP accounts, public research pages, researcher profiles, editorial workflows, Research Rooms, Data Lab, Policy Tracker, Trust Vault, contact forms and related platform services.']},
{title:'2. Information we collect',paragraphs:['We collect information you provide directly, information generated through use of the platform and limited technical information needed to secure and operate the service.'],bullets:['Account information such as name, email address, country, institution, profile details and authentication records.','Research information such as manuscripts, publication metadata, revisions, editorial actions, Trust Vault fingerprints and access history.','Collaboration information such as messages, Research Room membership and posts.','Technical and security information such as IP address, user agent, authentication events and abuse-prevention logs.','Usage information such as publication views, downloads, source clicks and tracked social referral events.']},
{title:'3. Why we process information',paragraphs:['AGP uses personal data to provide accounts and authentication, operate editorial and publishing workflows, protect research submissions, support collaboration, provide analytics, respond to enquiries, prevent abuse and improve platform reliability. We do not sell personal information to advertisers.']},
{title:'4. Research manuscripts and confidentiality',paragraphs:['Unpublished manuscripts are treated as confidential research material. Access is restricted to the author and authorised editorial personnel who are assigned to the submission and have completed the required confidentiality and conflict-of-interest steps. AGP does not intentionally send unpublished manuscripts to third-party generative AI services without explicit author consent.']},
{title:'5. Service providers and international processing',paragraphs:['AGP may use infrastructure, database, storage, transactional email, analytics and security providers to operate the platform. These providers may process information in countries outside the user’s country of residence. AGP seeks to use appropriate contractual, technical and organisational safeguards where required.']},
{title:'6. Cookies and authentication',paragraphs:['AGP uses essential cookies or equivalent session technologies to keep users signed in, complete multi-factor authentication and protect secure areas. We aim to avoid unnecessary tracking technologies.']},
{title:'7. Retention',paragraphs:['We retain account and platform records for as long as needed to provide the service, maintain research integrity, comply with legal obligations, resolve disputes and preserve legitimate publication records. Unpublished or withdrawn submissions may require limited integrity and audit records even where manuscript files are later removed.']},
{title:'8. Your rights',paragraphs:['Depending on applicable law, users may request access, correction, deletion, restriction, portability or objection in relation to personal information. Certain rights may be limited where retention is necessary for publication integrity, legal claims, security, archiving or other lawful purposes.']},
{title:'9. Security',paragraphs:['AGP uses measures including email verification, login MFA, dedicated editorial TOTP authentication, role-based access controls, private manuscript storage, hashed credentials, audit logs and Trust Vault access records. No online service can guarantee absolute security.']},
{title:'10. Applicable privacy frameworks',paragraphs:['AGP is based in Nigeria and intends to operate consistently with the Nigeria Data Protection Act 2023 and related guidance. Where the GDPR or another applicable privacy law applies to a user or processing activity, AGP will seek to honour the rights and obligations required by that law.']},
{title:'11. Changes',paragraphs:['We may update this policy as AGP develops. Material changes will be reflected by an updated effective date and, where appropriate, a prominent notice.']}
]}/>} 
