import PolicyPage from '../components/PolicyPage'
export default function Terms(){return <PolicyPage eyebrow="TERMS & CONDITIONS" title="Clear rules for a serious research platform." intro="These Terms govern use of Africa & Global Power and are intended to protect researchers, readers, editors and the integrity of the platform." updated="5 October 2026" sections={[
{title:'1. Acceptance and eligibility',paragraphs:['By creating an account or using AGP, you agree to these Terms and applicable policies. You must provide accurate account information and be legally capable of accepting these Terms or have any authorisation required by applicable law.']},
{title:'2. Accounts and security',paragraphs:['You are responsible for safeguarding your credentials, authenticator access and recovery codes. Do not share editorial accounts or attempt to bypass access controls. AGP may suspend access where necessary to protect users, research or platform security.']},
{title:'3. Research submissions',paragraphs:['You must have the right to submit all materials you upload. Submissions must not knowingly contain plagiarism, fabricated evidence, unlawful material, malicious files or content that infringes another person’s rights. Authors remain responsible for the accuracy and integrity of their work.']},
{title:'4. Author ownership and AGP licence',paragraphs:['Authors retain ownership of their original research unless a separate written agreement states otherwise. By publishing through AGP, the author grants AGP a non-exclusive licence to host, reproduce, format, display, preserve, index, promote and distribute the published work and related metadata for the operation and promotion of the platform. This licence does not transfer copyright ownership to AGP.']},
{title:'5. Unpublished work',paragraphs:['Submission to editorial review does not make a manuscript public. AGP will restrict manuscript access according to its Trust Vault and editorial controls. Authors should not treat the Trust Vault as a substitute for formal intellectual-property registration where such registration is appropriate.']},
{title:'6. Editorial independence',paragraphs:['Submission does not guarantee acceptance or publication. AGP may request revisions, reject submissions, correct published work, issue notices, withdraw material or retract publications where necessary to protect research integrity, safety or legal compliance.']},
{title:'7. Research Rooms and community conduct',paragraphs:['Users must engage professionally. Harassment, impersonation, threats, spam, malicious links, unauthorised disclosure of confidential material and attempts to compromise accounts or infrastructure are prohibited. Room owners and AGP may remove material or restrict participation where these rules are breached.']},
{title:'8. Data Lab and external sources',paragraphs:['Datasets, policy records and opportunities may link to third-party sources. AGP does not control external sites and cannot guarantee their continued availability. Users must observe the original source’s licence, terms and attribution requirements.']},
{title:'9. No professional advice',paragraphs:['AGP research and platform content is provided for research, education and public-interest information. It is not a substitute for legal, financial, medical, investment or other regulated professional advice.']},
{title:'10. Availability and changes',paragraphs:['AGP may modify, suspend or discontinue features where reasonably necessary for security, maintenance, legal compliance or product development. We aim to preserve published scholarly records and provide reasonable notice for material service changes where practicable.']},
{title:'11. Liability',paragraphs:['To the extent permitted by law, AGP is not responsible for indirect losses arising solely from reliance on user-generated content, external links or temporary service interruption. Nothing in these Terms excludes liability that cannot lawfully be excluded.']},
{title:'12. Governing framework and disputes',paragraphs:['These Terms are intended to operate under applicable Nigerian law, subject to any mandatory rights a user has under the laws that apply to them. Users should first contact AGP in good faith so disputes can be reviewed and resolved where possible.']}
]}/>} 
